
[build]
  command = "npm run build"
  publish = "dist"
  [build.environment]
    NODE_VERSION = "18.17.0"
    NPM_VERSION = "9.6.7"
    CI = "false"

# Règles de redirection pour SPA React (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# En-têtes de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.supabase.co"
    X-Content-Type-Options = "nosniff"

# Configuration du cache pour améliorer les performances
[[headers]]
  for = "/*.js" 
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
